In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import requests

In [2]:
url="https://www.politifact.com/factchecks/list/"
data=requests.get(url)
html=data.text
data.status_code

200

In [3]:
soup=BeautifulSoup(html,"html.parser")

In [4]:
x=soup.find_all("li",class_="o-listicle__item")
name = []
state = []
date = []
author = []
for i in x:
    n=i.find("a",class_="m-statement__name").text.strip()
    name.append(n)
    s=i.find("div",class_="m-statement__quote").text.strip()
    state.append(s)
    d=i.find("footer",class_="m-statement__footer").text.strip().split("•")[1]
    date.append(d)
    a=i.find("footer",class_="m-statement__footer").text.strip().split("•")[0]
    author.append(a)
df=pd.DataFrame({"name":name,"state":state,"date":date,"author":author})
df

,name,state,date,author
0,Donald Trump,"""There's been numerous other occasions over th...","May 20, 2026",By Louis Jacobson
1,Social Media,“San Diego mosque shooters identified as trans...,"May 20, 2026",By Jeff Cercone
2,X posts,"Video shows U.S. Rep. Byron Donalds saying, “I...","May 15, 2026",By Loreben Tuquero
3,X posts,An American passenger on the cruise ship invol...,"May 14, 2026",By Maria Briceño
4,Kathy Castor,“Florida is the only state in the nation kicki...,"May 14, 2026",By Samantha Putterman
5,Vivek Ramaswamy,"In 2020, “Amy Acton called off Ohio’s election...","May 13, 2026",By Amy Sherman
6,TikTok posts,Imágenes muestran a personas “infectadas con H...,"May 13, 2026",By Maria Briceño
7,Christine Quinn,"“Today, there are more children sleeping in Ne...","May 11, 2026",By Andrew McGurl
8,Nicholas Langworthy,“The average IRS tax refund is up 11% compared...,"May 11, 2026",By Holden Turek
9,Donald Trump,Gasoline prices have “come down very substanti...,"May 8, 2026",By Louis Jacobson
10,Byron Donalds,Congress passed the 1965 Voting Rights Act bec...,"May 8, 2026",By Samantha Putterman
11,Marcy Kaptur,Republicans “want you to pay $1 Billion for a ...,"May 8, 2026",By Maria Briceño
12,Liz Krueger,Proposed data centers in New York state would ...,"May 7, 2026",By Conor Amendola
13,X posts,“California only has ‘enough’ oil and gas supp...,"May 7, 2026",By Louis Jacobson
14,Donald Trump,"“Consumer confidence is way up.""","May 6, 2026",By Louis Jacobson
15,Sam Sutton,"From January 2025 to January 2026, “hate crime...","May 5, 2026",By Emma Gavazzi
16,Fentrice Driskell,"“Under federal law, you cannot engage in parti...","May 1, 2026",By Samantha Putterman
17,Instagram posts,Imagen muestra que “950 inmigrantes derrumbaro...,"April 30, 2026",By Maria Briceño
18,Bernie Sanders,“As a result of the 'Big Beautiful Bill' 15 mi...,"April 30, 2026",By Amy Sherman
19,Tim Scott,“Secret Service remains unpaid” during the par...,"April 29, 2026",By Louis Jacobson
20,Pine Tree Results PAC,“Graham Platner blames Maine’s women for getti...,"April 29, 2026",By Amy Sherman
21,Social Media,Video shows “unedited raw security footage” of...,"April 29, 2026",By Maria Briceño
22,Donald Trump,“We are right now producing more oil than Saud...,"April 29, 2026",By Louis Jacobson
23,Ron DeSantis,"Since the 2020 census, Florida has ""moved from...","April 29, 2026",By Louis Jacobson
24,Social Media,"“Tras el atentado a Trump”, en la cena de corr...","April 28, 2026",By Maria Briceño
25,Jay Collins,"U.S. Rep. Byron Donalds voted ""against three p...","April 23, 2026",By Samantha Putterman
26,Robert F. Kennedy Jr.,"""There's two ways of calculating percentage"" d...","April 23, 2026",By Louis Jacobson
27,Joe Rogan,"“With one dose of ibogaine, more than 80% of p...","April 22, 2026",By Grace Abels
28,X posts,“Newly released FOIA door logs show that forme...,"April 22, 2026",By Maria Briceño
29,Chris Wright,Solar and wind have not reached “3% of global ...,"April 22, 2026",By Louis Jacobson

In [12]:
url="https://www.cricbuzz.com/cricket-series/9241/indian-premier-league-2026/points-table"
data=requests.get(url)
html=data.text
data.status_code

200

In [18]:
soup=BeautifulSoup(html,"html.parser")

In [95]:
x = soup.find_all("div",class_="grid point-table-grid p-2 cursor-pointer")
name=[]
played=[]
won=[]
lost=[]
nr=[]
pts=[]
nrr=[]
n=soup.find_all("div",class_="flex flex-row items-center gap-1")
for i in n:
    n1=i.find("span",class_="text-gray-600").text
    name.append(n1)
for i in x:
    a=i.find_all("div",class_="flex justify-start items-center text-sm text-cbPointsTableTextGrey")
    for j in a[2]:
        played.append(j.text)
    for j in a[3]:
        won.append(j)
    for j in a[4]:
        lost.append(j)
    for j in a[5]:
        nr.append(j)
    for j in a[6]:
        nrr.append(j)
s=soup.find_all("div",class_="flex justify-start items-center text-sm font-bold text-gray-800")
for i in s:
    pts.append(i.text)

played=played[1:]
won=won[1:]
lost=lost[1:]
nr=nr[1:]
nrr=nrr[1:]
df=pd.DataFrame({"TEAMS":name,"P":played,"W":won,"L":lost,"NR":nr,"PTS":pts,"NRR":nrr})
df

  TEAMS   P  W  L NR PTS     NRR
0   RCB  13  9  4  0  18  +1.065
1    GT  13  8  5  0  16  +0.400
2   SRH  13  8  5  0  16  +0.350
3    RR  13  7  6  0  14  +0.083
4  PBKS  13  6  6  1  13  +0.227
5   KKR  13  6  6  1  13  +0.011
6   CSK  13  6  7  0  12  -0.016
7    DC  13  6  7  0  12  -0.871
8    MI  13  4  9  0   8  -0.510
9   LSG  13  4  9  0   8  -0.702