In [33]:
import requests
import json
import pandas as pd
import plotly.express as px
import plotly.io as pio
pio.renderers.default = "notebook"

In [2]:
lat=23.033863
lon=72.585022
key="57ed3a63cbe79efa475d0ab0b2f29b27"
url=f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={key}"
data=requests.get(url)
data.status_code

200

In [13]:
new=data.json()
final=json.dumps(new,indent=5)
print(final)

{
     "coord": {
          "lon": 72.585,
          "lat": 23.0339
     },
     "weather": [
          {
               "id": 711,
               "main": "Smoke",
               "description": "smoke",
               "icon": "50d"
          }
     ],
     "base": "stations",
     "main": {
          "temp": 309.18,
          "feels_like": 308.05,
          "temp_min": 309.18,
          "temp_max": 309.18,
          "pressure": 1008,
          "humidity": 24,
          "sea_level": 1008,
          "grnd_level": 1002
     },
     "visibility": 4000,
     "wind": {
          "speed": 2.57,
          "deg": 190
     },
     "clouds": {
          "all": 0
     },
     "dt": 1779431025,
     "sys": {
          "type": 1,
          "id": 9049,
          "country": "IN",
          "sunrise": 1779409577,
          "sunset": 1779457596
     },
     "timezone": 19800,
     "id": 1279233,
     "name": "Ahmedabad",
     "cod": 200
}

In [18]:
df=pd.DataFrame({"name":[new["name"]],"timezone":[new["timezone"]],"country":[new["sys"]["country"]],"wind speed":[new["wind"]["speed"]],
                 "visibility":[new["visibility"]],"description":[new["weather"][0]["description"]]})
df

        name  timezone country  wind speed  visibility description
0  Ahmedabad     19800      IN        2.57        4000       smoke

In [19]:
lat=23.033863
lon=72.585022
key="57ed3a63cbe79efa475d0ab0b2f29b27"
url=f"https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={key}"
data=requests.get(url)
data.status_code

200

In [20]:
new=data.json()
final=json.dumps(new,indent=5)
print(final)

{
     "cod": "200",
     "message": 0,
     "cnt": 40,
     "list": [
          {
               "dt": 1779440400,
               "main": {
                    "temp": 311.16,
                    "feels_like": 310.05,
                    "temp_min": 311.16,
                    "temp_max": 315.12,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 999,
                    "humidity": 21,
                    "temp_kf": -3.96
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.91,
                    "deg": 274,
                    "gust": 5.62
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-22 09:00:00"
          },
          {
               "dt": 1779451200,
               "main": {
                    "temp": 312.97,
                    "feels_like": 311.98,
                    "temp_min": 312.97,
                    "temp_max": 314.86,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 998,
                    "humidity": 19,
                    "temp_kf": -1.89
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.4,
                    "deg": 293,
                    "gust": 5.95
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-22 12:00:00"
          },
          {
               "dt": 1779462000,
               "main": {
                    "temp": 309.66,
                    "feels_like": 309.35,
                    "temp_min": 309.66,
                    "temp_max": 309.66,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1000,
                    "humidity": 27,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.2,
                    "deg": 218,
                    "gust": 6.74
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-22 15:00:00"
          },
          {
               "dt": 1779472800,
               "main": {
                    "temp": 305.56,
                    "feels_like": 308.81,
                    "temp_min": 305.56,
                    "temp_max": 305.56,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1001,
                    "humidity": 52,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 2.46,
                    "deg": 220,
                    "gust": 3.74
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-22 18:00:00"
          },
          {
               "dt": 1779483600,
               "main": {
                    "temp": 304.29,
                    "feels_like": 306.21,
                    "temp_min": 304.29,
                    "temp_max": 304.29,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1000,
                    "humidity": 51,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.87,
                    "deg": 273,
                    "gust": 7.62
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-22 21:00:00"
          },
          {
               "dt": 1779494400,
               "main": {
                    "temp": 302.7,
                    "feels_like": 304.97,
                    "temp_min": 302.7,
                    "temp_max": 302.7,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1002,
                    "humidity": 59,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.36,
                    "deg": 270,
                    "gust": 8.19
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 00:00:00"
          },
          {
               "dt": 1779505200,
               "main": {
                    "temp": 305.18,
                    "feels_like": 307.1,
                    "temp_min": 305.18,
                    "temp_max": 305.18,
                    "pressure": 1010,
                    "sea_level": 1010,
                    "grnd_level": 1004,
                    "humidity": 48,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 801,
                         "main": "Clouds",
                         "description": "few clouds",
                         "icon": "02d"
                    }
               ],
               "clouds": {
                    "all": 13
               },
               "wind": {
                    "speed": 5.08,
                    "deg": 283,
                    "gust": 6.41
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 03:00:00"
          },
          {
               "dt": 1779516000,
               "main": {
                    "temp": 311.29,
                    "feels_like": 311.56,
                    "temp_min": 311.29,
                    "temp_max": 311.29,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 26,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 802,
                         "main": "Clouds",
                         "description": "scattered clouds",
                         "icon": "03d"
                    }
               ],
               "clouds": {
                    "all": 29
               },
               "wind": {
                    "speed": 4.89,
                    "deg": 266,
                    "gust": 6.02
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 06:00:00"
          },
          {
               "dt": 1779526800,
               "main": {
                    "temp": 314.92,
                    "feels_like": 315.13,
                    "temp_min": 314.92,
                    "temp_max": 314.92,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 999,
                    "humidity": 20,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 802,
                         "main": "Clouds",
                         "description": "scattered clouds",
                         "icon": "03d"
                    }
               ],
               "clouds": {
                    "all": 30
               },
               "wind": {
                    "speed": 5.73,
                    "deg": 254,
                    "gust": 6.65
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 09:00:00"
          },
          {
               "dt": 1779537600,
               "main": {
                    "temp": 314.6,
                    "feels_like": 313.91,
                    "temp_min": 314.6,
                    "temp_max": 314.6,
                    "pressure": 1003,
                    "sea_level": 1003,
                    "grnd_level": 998,
                    "humidity": 18,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 802,
                         "main": "Clouds",
                         "description": "scattered clouds",
                         "icon": "03d"
                    }
               ],
               "clouds": {
                    "all": 50
               },
               "wind": {
                    "speed": 6.6,
                    "deg": 300,
                    "gust": 6.46
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 12:00:00"
          },
          {
               "dt": 1779548400,
               "main": {
                    "temp": 309.05,
                    "feels_like": 309.67,
                    "temp_min": 309.05,
                    "temp_max": 309.05,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 32,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 804,
                         "main": "Clouds",
                         "description": "overcast clouds",
                         "icon": "04n"
                    }
               ],
               "clouds": {
                    "all": 100
               },
               "wind": {
                    "speed": 3.61,
                    "deg": 225,
                    "gust": 6.37
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 15:00:00"
          },
          {
               "dt": 1779559200,
               "main": {
                    "temp": 305.75,
                    "feels_like": 306.31,
                    "temp_min": 305.75,
                    "temp_max": 305.75,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1001,
                    "humidity": 40,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 803,
                         "main": "Clouds",
                         "description": "broken clouds",
                         "icon": "04n"
                    }
               ],
               "clouds": {
                    "all": 73
               },
               "wind": {
                    "speed": 4.68,
                    "deg": 255,
                    "gust": 8.63
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 18:00:00"
          },
          {
               "dt": 1779570000,
               "main": {
                    "temp": 302.76,
                    "feels_like": 304.4,
                    "temp_min": 302.76,
                    "temp_max": 302.76,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 55,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.37,
                    "deg": 252,
                    "gust": 9.85
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 21:00:00"
          },
          {
               "dt": 1779580800,
               "main": {
                    "temp": 301.54,
                    "feels_like": 304.14,
                    "temp_min": 301.54,
                    "temp_max": 301.54,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1002,
                    "humidity": 67,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 1
               },
               "wind": {
                    "speed": 4.75,
                    "deg": 282,
                    "gust": 8.77
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-24 00:00:00"
          },
          {
               "dt": 1779591600,
               "main": {
                    "temp": 304.26,
                    "feels_like": 306.36,
                    "temp_min": 304.26,
                    "temp_max": 304.26,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 1003,
                    "humidity": 52,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 2
               },
               "wind": {
                    "speed": 6.25,
                    "deg": 267,
                    "gust": 8.1
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 03:00:00"
          },
          {
               "dt": 1779602400,
               "main": {
                    "temp": 311.12,
                    "feels_like": 311.29,
                    "temp_min": 311.12,
                    "temp_max": 311.12,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1002,
                    "humidity": 26,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.21,
                    "deg": 263,
                    "gust": 7.46
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 06:00:00"
          },
          {
               "dt": 1779613200,
               "main": {
                    "temp": 315.58,
                    "feels_like": 314.53,
                    "temp_min": 315.58,
                    "temp_max": 315.58,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 999,
                    "humidity": 16,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 3
               },
               "wind": {
                    "speed": 6.41,
                    "deg": 271,
                    "gust": 6.83
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 09:00:00"
          },
          {
               "dt": 1779624000,
               "main": {
                    "temp": 315.04,
                    "feels_like": 313.82,
                    "temp_min": 315.04,
                    "temp_max": 315.04,
                    "pressure": 1003,
                    "sea_level": 1003,
                    "grnd_level": 997,
                    "humidity": 16,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 2
               },
               "wind": {
                    "speed": 6.76,
                    "deg": 280,
                    "gust": 6.76
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 12:00:00"
          },
          {

In [30]:
temp=[]
date=[]
time=[]
dis=[]
for i in new["list"]:
    temp.append(i["main"]["temp"])
    date.append(i["dt_txt"].split(" ")[0])
    time.append(i["dt_txt"].split(" ")[1])
    dis.append(i["weather"][0]["description"])    
df=pd.DataFrame({"temp":temp,"date":date,"time":time,"dis":dis})
df

      temp        date      time               dis
0   311.16  2026-05-22  09:00:00         clear sky
1   312.97  2026-05-22  12:00:00         clear sky
2   309.66  2026-05-22  15:00:00         clear sky
3   305.56  2026-05-22  18:00:00         clear sky
4   304.29  2026-05-22  21:00:00         clear sky
5   302.70  2026-05-23  00:00:00         clear sky
6   305.18  2026-05-23  03:00:00        few clouds
7   311.29  2026-05-23  06:00:00  scattered clouds
8   314.92  2026-05-23  09:00:00  scattered clouds
9   314.60  2026-05-23  12:00:00  scattered clouds
10  309.05  2026-05-23  15:00:00   overcast clouds
11  305.75  2026-05-23  18:00:00     broken clouds
12  302.76  2026-05-23  21:00:00         clear sky
13  301.54  2026-05-24  00:00:00         clear sky
14  304.26  2026-05-24  03:00:00         clear sky
15  311.12  2026-05-24  06:00:00         clear sky
16  315.58  2026-05-24  09:00:00         clear sky
17  315.04  2026-05-24  12:00:00         clear sky
18  310.15  2026-05-24  15:00:00         clear sky
19  305.30  2026-05-24  18:00:00         clear sky
20  302.99  2026-05-24  21:00:00         clear sky
21  301.37  2026-05-25  00:00:00         clear sky
22  304.23  2026-05-25  03:00:00         clear sky
23  311.83  2026-05-25  06:00:00         clear sky
24  316.44  2026-05-25  09:00:00         clear sky
25  315.20  2026-05-25  12:00:00         clear sky
26  309.17  2026-05-25  15:00:00         clear sky
27  305.26  2026-05-25  18:00:00         clear sky
28  302.76  2026-05-25  21:00:00         clear sky
29  301.94  2026-05-26  00:00:00         clear sky
30  304.68  2026-05-26  03:00:00         clear sky
31  311.84  2026-05-26  06:00:00         clear sky
32  316.30  2026-05-26  09:00:00         clear sky
33  315.77  2026-05-26  12:00:00         clear sky
34  307.24  2026-05-26  15:00:00         clear sky
35  304.91  2026-05-26  18:00:00         clear sky
36  303.37  2026-05-26  21:00:00         clear sky
37  301.88  2026-05-27  00:00:00         clear sky
38  304.28  2026-05-27  03:00:00         clear sky
39  311.44  2026-05-27  06:00:00         clear sky